spring:
    # activiti
  activiti:
    #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
    database-schema-update: true
    #在项目单独作为一个引擎，本身不部署流程的时候，如果resources目录没有“processes”目录，启动项目报错–找不到processes目录。需要在配置文件中添加以下内容：
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes:
      -**.bpmn
      -**.bpmn20.xml
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full